# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
a=np.random.random((3,3,3))
print(a)

[[[0.14598615 0.36176036 0.68414664]
  [0.72169398 0.7867299  0.2482001 ]
  [0.18207815 0.30806046 0.79662139]]

 [[0.31963298 0.30015504 0.33151396]
  [0.98406557 0.93456549 0.60310632]
  [0.73119927 0.22552772 0.94990766]]

 [[0.35079783 0.33860669 0.52978964]
  [0.09328299 0.57725152 0.85243351]
  [0.33326705 0.90686789 0.03833253]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
x=np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
x=np.ones((3,3))
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [10]:
x=np.random.random((5,5))
print("Original Array:",x)
xmax,xmin=x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
print("After Normalization:",x)

Original Array: [[0.62339975 0.74103349 0.42722106 0.53777948 0.50067905]
 [0.8516805  0.35226907 0.04415862 0.02969746 0.60085122]
 [0.2757081  0.3571664  0.45745636 0.96044957 0.54739183]
 [0.5524056  0.11551614 0.5623884  0.0812001  0.45469211]
 [0.30705641 0.70755359 0.66418919 0.61136047 0.28581689]]
After Normalization: [[0.6378737  0.76425938 0.42709932 0.54588328 0.50602259]
 [0.88313853 0.34657092 0.01553707 0.         0.61364756]
 [0.26431381 0.35183261 0.45958413 1.         0.55621079]
 [0.56159759 0.09220358 0.57232311 0.05533443 0.45661422]
 [0.29799444 0.72828858 0.68169787 0.62493869 0.2751747 ]]


# 5.  How to find common values between two arrays?

In [11]:
array_1=np.array([1,2,3,4,5,6])
print("Array_1:",array_1)
array_2=[10,4,11,7,5,2]
print("Array_2:",array_2)
ans=np.intersect1d(array_1,array_2)
print("Common values are:",ans)

Array_1: [1 2 3 4 5 6]
Array_2: [10, 4, 11, 7, 5, 2]
Common values are: [2 4 5]


# 6.How to get the dates of yesterday, today and tomorrow?

In [12]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [14]:
a=np.random.random((3,3))
print("array_1:")
print(a)
b=np.random.random((3,3))
print("array_2:")
print(b)
array_equal=np.allclose(a,b)
print(array_equal)


array_1:
[[0.18812333 0.99403252 0.39646293]
 [0.0546827  0.45047724 0.30812809]
 [0.22273566 0.44346779 0.49054482]]
array_2:
[[0.84079428 0.77883695 0.74892692]
 [0.44993234 0.9612728  0.63074181]
 [0.73961212 0.94747352 0.28475005]]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [15]:
x=np.random.random(10)
print("Original Array:")
print(x)
x[x.argmax()]=0
print("Maximum Value replaced by 0:")
print(x)

Original Array:
[0.37813777 0.50335057 0.20475772 0.89875227 0.6478007  0.97298315
 0.1830486  0.23004524 0.60733771 0.86161387]
Maximum Value replaced by 0:
[0.37813777 0.50335057 0.20475772 0.89875227 0.6478007  0.
 0.1830486  0.23004524 0.60733771 0.86161387]


# 9. How to print all the values of an array?

In [16]:
array=np.arange(20)
np.set_printoptions(threshold=np.inf)
print("All values of the array are:")
print(array)

All values of the array are:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# 10.Subtract the mean of each row of a matrix

In [17]:
print("Original matrix:\n")
X = np.random.rand(3,4)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.14487654 0.21096827 0.72082213 0.26582925]
 [0.37297174 0.2485453  0.86189706 0.63829932]
 [0.03608074 0.68434801 0.49216319 0.38462006]]

Subtract the mean of each row of the said matrix:

[[-0.1907475  -0.12465578  0.38519808 -0.0697948 ]
 [-0.15745662 -0.28188306  0.33146871  0.10787097]
 [-0.36322226  0.28504502  0.09286019 -0.01468294]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [18]:
x=np.ones(10)
y=np.random.randint(0,len(x),20)
x+=np.bincount(y,minlength=len(x))
print(x)

[4. 2. 2. 5. 1. 1. 2. 5. 4. 4.]


# 12.How to get the diagonal of a dot product?

In [19]:
x=np.random.uniform(0,1,(5,5))
y=np.random.uniform(0,1,(5,5))
np.diag(np.dot(x,y))

array([0.75645591, 1.2083381 , 0.79343512, 1.02231614, 0.53315604])

# 13.How to find the most frequent value in an array?

In [20]:
x=np.random.randint(0,3,6)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 1 0 0 0 0]
Most frequent value in the above array:
0


# 14.How to get the n largest values of an array

In [22]:
x=np.arange(15)
print("Original Array:")
print(x)
np.random.shuffle(x)
n=1
print(x[np.argsort(x)[-n:]])

Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14]


# 15.How to create a record array from a regular array?

In [23]:
arra1 = np.array([("pushpa", 88.5, 90),
                 ("raju", 87, 99),
             ("rita", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='col1, col2, col3',
                              formats = 'S80, f8, i8')
print(result)

Original arrays:
[['pushpa' '88.5' '90']
 ['raju' '87' '99']
 ['rita' '85.5' '91']]

Record array;
[(b'pushpa', 88.5, 90) (b'raju', 87. , 99) (b'rita', 85.5, 91)]
